modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="chilean_records"
version="${file.jarVersion}"
displayName="Chileam Records"
#logoFile="chilean_records.png"
credits="""
Thanks to Javitoire for record the demo <3
Thanks to my country for having this beautiful records."""
authors="Sheloire"
description='''
Adds 3 Music Discs with national records:
 1. Chilean Official Anthem.
 2. Jaime Atria - La consentida.
 3. Los 4 Cuartos - Los Viejos Estandartes.
'''
[[dependencies.chilean_records]] #optional
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chilean_records]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
