modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="chilean_records"
version="${file.jarVersion}"
displayName="Chilean Records"
displayURL="https://www.curseforge.com/minecraft/mc-mods/chilean-records"
logoFile="chilean_records.png"
credits="""


 Thanks to Javitoire for record the demo <3
 Thanks to Xarlord and ElmoHD for help with the songs.
"""
authors="Sheloire"
description="""
Adds 9 Music Discs with national records:
 1. Chilean National Anthem
 2. La Consentida - Jaime Atria
 3. Los Viejos Estandartes - Los 4 Cuartos
 4. Un Año Más - La Sonora de Tommy Rey
 5. Tren al sur - Los Prisioneros
 6. Falso Amor - Los Picantes
 7. Curao Manejor Mejor - Los Mox
 8. La Mejicana - Tata Barahona
 9. Mortal Kumbiat - Leo Rey
"""
[[dependencies.chilean_records]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chilean_records]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
